using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace StoneDocuments
{
    /// <summary>
    /// Interaction logic for frmReportBugs.xaml
    /// </summary>
    public partial class frmReportBugs : Window
    {
        ObservableCollection<string> CommandData { get; set; }

        public frmReportBugs(List<string> CommandList)
        {
            InitializeComponent();

            CommandData = new ObservableCollection<string>(CommandList);

            cmbCommands.ItemsSource = CommandData;

            // Set focus to command name combobox when window loads
            this.Loaded += (s, e) => cmbCommands.Focus();
        }

        private void SendButton_Click(object sender, RoutedEventArgs e)
        {
            // Validate input
            if (string.IsNullOrWhiteSpace(cmbCommands.Text))
            {
                System.Windows.MessageBox.Show("Please enter the command name.", "Validation Error",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                cmbCommands.Focus();
                return;
            }

            if (string.IsNullOrWhiteSpace(DescriptionTextBox.Text))
            {
                System.Windows.MessageBox.Show("Please enter a description of the error.", "Validation Error",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                DescriptionTextBox.Focus();
                return;
            }

            try
            {
                SendBugReport();
                this.DialogResult = true;
                this.Close();
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show($"Failed to send bug report: {ex.Message}", "Error",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = false;
            this.Close();
        }

        private void SendBugReport()
        {
            string subject = $"Bug Report - {cmbCommands.Text}";
            string body = $@"
Bug Report Details:
==================

Command Name: {cmbCommands.Text}
Date/Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
User: {Environment.UserName}
Computer: {Environment.MachineName}

Error Description:
{DescriptionTextBox.Text}

==================
This bug report was automatically generated by the Revit Bug Report Tool.
";

            try
            {
                // Open the default email client with pre-populated fields
                string encodedSubject = Uri.EscapeDataString(subject);
                string encodedBody = Uri.EscapeDataString(body);
                string mailtoUrl = $"mailto:bim.manager@lusad.com?subject={encodedSubject}&body={encodedBody}";

                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = mailtoUrl,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                // Fallback: Copy to clipboard and show instructions
                System.Windows.Clipboard.SetText($"Subject: {subject}\n\n{body}");

                System.Windows.MessageBox.Show($"Could not open email client automatically.\n\n" +
                              $"The bug report details have been copied to your clipboard.\n" +
                              $"Please manually paste them into an email to: bim.manager@lusad.com\n\n" +
                              $"Error: {ex.Message}",
                    "Email Client Error", MessageBoxButton.OK, MessageBoxImage.Information);
            }
        }
    }
}
